databases:
  # DEV Database (Only one allowed on Free Tier)
  - name: bulky-db-dev
    plan: free
    databaseName: bulky_dev
    user: bulky_user

services:
  # DEV Web Service
  - type: web
    name: bulky-web-dev
    runtime: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: bulky-db-dev
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
