services:
  # DEV Environment
  - type: web
    name: bulky-web-dev
    runtime: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: bulky-db-dev
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Development

  - type: psql
    name: bulky-db-dev
    plan: free
    databaseName: bulky_dev
    user: bulky_user

  # TEST Environment
  - type: web
    name: bulky-web-test
    runtime: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: bulky-db-test
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Staging

  - type: psql
    name: bulky-db-test
    plan: free
    databaseName: bulky_test
    user: bulky_user

  # PROD Environment
  - type: web
    name: bulky-web-prod
    runtime: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: bulky-db-prod
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: psql
    name: bulky-db-prod
    plan: free
    databaseName: bulky_prod
    user: bulky_user
